### ISSUE TITLE
디미고인 급식 API 오류

### ISSUE THREAD

**Issue by MinSeungHyun** [dimigoin/dimigoin-android#4]
디미고인 급식 API가 제대로된 급식 정보를 불러오지 못하는 것 같아 `/dimibobs/{date}` 이 API를 사용해야할 것 같습니다

**Comment by wkdwhddn06** [comment]
> 디미고인 급식 API가 제대로된 급식 정보를 불러오지 못하는 것 같아 `/dimibobs/{date}` 이 API를 사용해야할 것 같습니다

벡엔드 쪽에 Fix 요청해주세요 아는 사람이 없어서... ㅋㅋㅋㅋㅋ

**Comment by MinSeungHyun** [comment]
안도르이드 쪽에서 저 API로 바꾸면 될 것 같습니다 :)

**Comment by wkdwhddn06** [comment]
> 안도르이드 쪽에서 저 API로 바꾸면 될 것 같습니다 :)

그래도 혹시 벡엔드 쪽에서도 모르고 있을 수 도 있으니까 ㅋㅋㅋ 말은 해둡시다 아니면 이슈를 올려도 좋겠네요

**Comment by MinSeungHyun** [comment]
백엔드쪽에 말 해봤는데 작년부터 요청을 했지만 안고쳐지고 있다고 하네요 ㅠㅠ 어차피 이제 새로운 API 나오니까 괜찮아요
