### ISSUE TITLE
Attendance search filter not automatically applied after refresh

### ISSUE THREAD

**Issue by nutyworks** [dimigoin/dimigoin-android#43]
**Steps to reproduce:**
1. Search with any name.
2. Refresh attendance.
3. Search filter not applied.

**Expected behavior:**
Search filter automatically applied after refresh.

**Comment by wkdwhddn06** [comment]
Fixed here : 1e35f37

This patch is included in 1.0.1 update. Update will release soon with some improvements.

Thank you for your report!
